package tui

// emojiEntry is one completable emoji: its canonical shortcode (shown in
// the completion list) and extra English and Spanish keywords, all
// lowercase ASCII (Spanish accents dropped, so ":corazon" and
// ":corazón" both match after normalization).
type emojiEntry struct {
	emoji    string
	code     string
	keywords string
}

// emojiTable is a curated set of the most used emoji, not all of
// Unicode: a completion list is only useful when the first few matches
// are the likely ones.
var emojiTable = []emojiEntry{
	{"😂", "joy", "risa llorar carcajada lol jaja laugh tears"},
	{"🤣", "rofl", "rodando risa carcajada jajaja"},
	{"😀", "grinning", "sonrisa feliz happy smile"},
	{"😃", "smiley", "sonrisa feliz happy"},
	{"😄", "smile", "sonrisa feliz happy"},
	{"😁", "grin", "sonrisa dientes"},
	{"😅", "sweat_smile", "risa nervios sudor uff"},
	{"😆", "laughing", "risa carcajada"},
	{"😉", "wink", "guino ojo"},
	{"😊", "blush", "sonrojo sonrisa feliz"},
	{"🙂", "slight_smile", "sonrisa leve"},
	{"🙃", "upside_down", "reves ironia"},
	{"😇", "innocent", "inocente angel"},
	{"😍", "heart_eyes", "enamorado amor ojos corazon"},
	{"🥰", "smiling_hearts", "amor enamorado corazones cariño"},
	{"😘", "kiss", "beso amor"},
	{"😗", "kissing", "beso"},
	{"😋", "yum", "rico delicioso sabroso"},
	{"😛", "tongue", "lengua"},
	{"😜", "wink_tongue", "lengua guino broma"},
	{"🤪", "zany", "loco locura"},
	{"🤔", "thinking", "pensar pensando duda hmm"},
	{"🤨", "raised_eyebrow", "ceja sospecha duda"},
	{"😐", "neutral", "neutral serio"},
	{"😑", "expressionless", "inexpresivo serio"},
	{"😶", "no_mouth", "sin boca callado"},
	{"🙄", "eye_roll", "ojos blanco fastidio"},
	{"😏", "smirk", "picaro sonrisa"},
	{"😬", "grimace", "mueca incomodo tenso"},
	{"🤐", "zipper_mouth", "callado secreto"},
	{"😌", "relieved", "aliviado tranquilo"},
	{"😔", "pensive", "triste pensativo"},
	{"😪", "sleepy", "sueño"},
	{"😴", "sleeping", "dormir durmiendo sueño zzz"},
	{"😷", "mask", "mascarilla enfermo"},
	{"🤒", "sick", "enfermo fiebre"},
	{"🤢", "nauseated", "asco nauseas"},
	{"🤮", "vomit", "vomito asco"},
	{"🥵", "hot", "calor caliente"},
	{"🥶", "cold", "frio congelado"},
	{"🤯", "mind_blown", "explota mente wow"},
	{"🥳", "party", "fiesta celebrar cumpleaños"},
	{"😎", "sunglasses", "lentes gafas cool genial"},
	{"🤓", "nerd", "nerd lentes"},
	{"😕", "confused", "confundido"},
	{"😟", "worried", "preocupado"},
	{"🙁", "frown", "triste"},
	{"😮", "open_mouth", "sorpresa asombro wow"},
	{"😲", "astonished", "asombrado sorpresa"},
	{"😳", "flushed", "sonrojado verguenza"},
	{"🥺", "pleading", "suplica porfa ojitos"},
	{"😢", "cry", "llorar triste lagrima"},
	{"😭", "sob", "llanto llorar triste"},
	{"😱", "scream", "grito miedo susto"},
	{"😖", "confounded", "frustrado"},
	{"😞", "disappointed", "decepcionado triste"},
	{"😓", "sweat", "sudor"},
	{"😩", "weary", "cansado agotado"},
	{"😫", "tired", "cansado agotado"},
	{"🥱", "yawn", "bostezo sueño aburrido"},
	{"😤", "triumph", "enojado resoplido"},
	{"😡", "rage", "enojado furioso ira"},
	{"😠", "angry", "enojado molesto"},
	{"🤬", "cursing", "insulto groseria furioso"},
	{"😈", "smiling_imp", "diablo travieso"},
	{"💀", "skull", "calavera muerto muerte"},
	{"💩", "poop", "caca"},
	{"🤡", "clown", "payaso"},
	{"👻", "ghost", "fantasma"},
	{"👽", "alien", "extraterrestre"},
	{"🤖", "robot", "robot bot"},
	{"🙈", "see_no_evil", "mono verguenza no ver"},
	{"🙉", "hear_no_evil", "mono no oir"},
	{"🙊", "speak_no_evil", "mono no hablar"},
	{"👍", "thumbsup", "pulgar arriba ok like bien si dale +1"},
	{"👎", "thumbsdown", "pulgar abajo no dislike mal -1"},
	{"👌", "ok_hand", "ok perfecto bien"},
	{"✌️", "v", "paz victoria"},
	{"🤞", "crossed_fingers", "dedos cruzados suerte ojala"},
	{"🤙", "call_me", "llamame shaka"},
	{"👋", "wave", "hola chau adios saludo mano"},
	{"👏", "clap", "aplauso aplausos bravo"},
	{"🙌", "raised_hands", "celebrar manos arriba"},
	{"🙏", "pray", "gracias por favor rezar rezo porfa"},
	{"🤝", "handshake", "trato acuerdo apreton manos"},
	{"💪", "muscle", "fuerza fuerte musculo animo"},
	{"👀", "eyes", "ojos mirar viendo"},
	{"👉", "point_right", "derecha señalar"},
	{"👈", "point_left", "izquierda señalar"},
	{"👆", "point_up", "arriba señalar"},
	{"👇", "point_down", "abajo señalar"},
	{"🫶", "heart_hands", "manos corazon amor"},
	{"❤️", "heart", "corazon amor rojo love"},
	{"🧡", "orange_heart", "corazon naranja"},
	{"💛", "yellow_heart", "corazon amarillo"},
	{"💚", "green_heart", "corazon verde"},
	{"💙", "blue_heart", "corazon azul"},
	{"💜", "purple_heart", "corazon morado"},
	{"🖤", "black_heart", "corazon negro"},
	{"🤍", "white_heart", "corazon blanco"},
	{"💔", "broken_heart", "corazon roto desamor"},
	{"💕", "two_hearts", "corazones amor"},
	{"💖", "sparkling_heart", "corazon brillante"},
	{"💯", "100", "cien perfecto"},
	{"🔥", "fire", "fuego genial candela"},
	{"✨", "sparkles", "brillos magia"},
	{"⭐", "star", "estrella"},
	{"🌟", "glowing_star", "estrella brillante"},
	{"💥", "boom", "explosion"},
	{"💤", "zzz", "dormir sueño"},
	{"💬", "speech", "mensaje chat globo"},
	{"🎉", "tada", "fiesta celebrar felicidades hurra"},
	{"🎊", "confetti", "confeti fiesta"},
	{"🎂", "cake", "torta pastel cumpleaños"},
	{"🎁", "gift", "regalo"},
	{"🎈", "balloon", "globo fiesta"},
	{"🏆", "trophy", "trofeo ganador campeon"},
	{"⚽", "soccer", "futbol pelota balon"},
	{"✅", "check", "listo hecho ok si correcto"},
	{"❌", "x", "no mal error cruz"},
	{"⚠️", "warning", "advertencia cuidado alerta"},
	{"❓", "question", "pregunta duda"},
	{"❗", "exclamation", "exclamacion importante"},
	{"➡️", "arrow_right", "flecha derecha"},
	{"⬅️", "arrow_left", "flecha izquierda"},
	{"🆗", "ok", "ok"},
	{"🆘", "sos", "ayuda emergencia"},
	{"☀️", "sun", "sol soleado"},
	{"🌙", "moon", "luna noche"},
	{"🌧️", "rain", "lluvia"},
	{"❄️", "snow", "nieve frio"},
	{"🌈", "rainbow", "arcoiris"},
	{"🌹", "rose", "rosa flor"},
	{"🌸", "cherry_blossom", "flor cerezo"},
	{"🍀", "clover", "trebol suerte"},
	{"☕", "coffee", "cafe"},
	{"🍺", "beer", "cerveza chela"},
	{"🍻", "beers", "cervezas salud brindis"},
	{"🍷", "wine", "vino"},
	{"🥂", "champagne", "brindis salud champan"},
	{"🍕", "pizza", "pizza"},
	{"🍔", "burger", "hamburguesa"},
	{"🌮", "taco", "taco"},
	{"🍰", "shortcake", "pastel postre"},
	{"🎵", "music", "musica nota"},
	{"📞", "phone", "telefono llamada llamar"},
	{"📱", "mobile", "celular movil telefono"},
	{"💻", "laptop", "computadora portatil"},
	{"📷", "camera", "camara foto"},
	{"📎", "paperclip", "clip adjunto"},
	{"📌", "pin", "chincheta fijar"},
	{"📅", "calendar", "calendario fecha"},
	{"⏰", "alarm", "alarma reloj hora"},
	{"💰", "money", "dinero plata"},
	{"💡", "bulb", "idea foco"},
	{"🔒", "lock", "candado seguro"},
	{"🚀", "rocket", "cohete rapido lanzamiento"},
	{"🚗", "car", "auto carro coche"},
	{"✈️", "airplane", "avion viaje vuelo"},
	{"🏠", "house", "casa hogar"},
	{"🐶", "dog", "perro"},
	{"🐱", "cat", "gato"},
	{"🙋", "raising_hand", "yo levantar mano"},
	{"🤷", "shrug", "no se encogerse ni idea"},
	{"🤦", "facepalm", "palmada cara"},
	{"🇵🇪", "peru", "peru bandera"},
}
